[project]
name = "fhempy"
description = "Python binding for FHEM to support Python modules"
version = "0.1.665"
authors = [
    { name = "Dominik Karall", email = "dominik.karall@gmail.com" }
]
readme="README.md"
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/fhempy/fhempy"
"Bug Tracker" = "https://github.com/fhempy/fhempy/issues"
"Sponsor" = "https://github.com/sponsors/fhempy"

[tool.setuptools]
include-package-data = true
script-files = ["FHEM/bindings/python/bin/fhempy"]

[tool.setuptools.packages.find]
where=["FHEM/bindings/python"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"*" = ["README.md"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
build_command = "python3 -m build"
